### ISSUE TITLE
Update Readme Example 

### ISSUE THREAD

**Issue by bander-saeed94** [halvardssm/deno-nessie#44]
The example needs to be updated.
I also wonder why the schema was removed from the input it was saving some typing. I understand the dialect was removed from the nessie.config.ts file however I think we only need it to be defined once.

query += ...; does not work anymore since the return type is string[]
```
import { Migration } from "https://deno.land/x/nessie/mod.ts";
import { Schema, dbDialects } from "https://deno.land/x/nessie/qb.ts";

const dialect: dbDialects = "mysql"

export const up: Migration = () => {

  let query = new Schema(dialect).create("users", (table) => {
    table.id();
    table.string("name", 100).nullable();
    table.boolean("is_true").default("false");
    table.custom("custom_column int default 1");
    table.timestamps();
  });

  query += new Schema(dialect).queryString(
    "INSERT INTO users VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);",
  );

  return query
};

export const down: Migration = () => {
  return new Schema(dialect).drop("users");
};
```

I think the ultimate would be something like:
```
import { Migration } from "https://deno.land/x/nessie/mod.ts";
import { Schema, dbDialects } from "https://deno.land/x/nessie/qb.ts";

const dialect: dbDialects = "mysql"

export const up: Migration = () => {
  const schema = new Schema(dialect);
  schema.create("users", (table) => {
    table.id();
    table.string("name", 100).nullable();
    table.boolean("is_true").default("false");
    table.custom("custom_column int default 1");
    table.timestamps();
  });

  schema.queryString(
    "INSERT INTO users VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);",
  );
  return schema.query;
};

export const down: Migration = () => {
  const schema = new Schema(dialect);
  schema.drop("users");
  return schema.query;
};
```

**Comment by halvardssm** [comment]
Hi @bander-saeed94 ! The schema was moved from the input to reduce the overhead for when you want to use other query builders i.e. Dex. So regarding defining the dialect only once, I agree it would be fewer lines per file, but ultimately it wouldn't work with the modular system for every query builder since each one uses different names for the databases (take postgres for example, we can use `pg`, `postgres`, `postgresql`, `pgsql`, `psql`) there are too many names to take into account. 

One thing which might be possible is to give 1 order integration for the Nessie query builder. What I mean by that is that we can expose an object in the up and down methods containing some basic information like dialect. This would, of course, be heavily dependent on the Clients available, but it is doable.

Regarding the readme; thanks! I must have forgotten to update the readme during the last PR. Will push an update now 👍

**Comment by halvardssm** [comment]
Readme is updated, so I will close this issue, but I will open a new one where we can discuss exposing schema in the migration files

**Comment by halvardssm** [comment]
#46
