### ISSUE TITLE
Doubt about Deno v.0.42

### ISSUE THREAD

**Issue by fvilante** [halvardssm/deno-nessie#8]
I just tried to execute [one arbitrary unit test](https://github.com/halvardssm/deno-nessie/blob/master/tests/column.test.ts) using the deno (v.0.42) instalated on my enviroment. Typing:

```
> deno test [link_to_test.ts]
```
But got an compilation Error.

My question: Is this I'm doing possible (calling a test without cloning the repository)? Should Deno work as I expected (fetch all the test dependencies and run the test in my machine giving the test result)? Or am I understanding deno wrong?

Because if I MUST clone the repository before run the test, what is the point of deno in relation to nodejs?

PS: I'm newcomer to Deno.
PS2: I think it could be just a temporarily break change, but would like someone more experienced than me to confirm. 
PS3: I saw you commit the upgrade code for v.0.42 just 3 hours ago.

Thank you!

#6 #7

**Comment by halvardssm** [comment]
Hi! That might be because I introuced import maps in v0.3.0 3 hours ago. I am actually considering to switch it over to using the deps import, i have a feeling it broke something with using the import maps. As Deno still has around two weeks until v1.0 I think there will be more changes introduced. 

I'll post an update soon 👍

**Comment by halvardssm** [comment]
@fvilante So I managed to figure out the issue. Deno is kind of new to me still so it takes a bit of trial and error to make sure everything works perfectly. 

The issue you were facing was because I was using import maps instead of using a dependencies file. It should now all be fixed in the latest release v0.3.3. If you try it out, you should be able to run the test now.

So to answer your question: Yes, the point of Deno is that you can run modules directly from a url. The security aspect is coming from the flags that you have to enable for the script to work, which makes you think twice before allowing something unknown running on your system. 

I hope this gave you some clarity into Deno :)

#9 #10 #11

**Comment by fvilante** [comment]
@halvardssm I found the mistake I have made. Just for your acknowledge here it is:

I was typing line (1) below and getting an error (E). When I typed line (2) below the test runned and passed.
```
(1) deno test https://raw.githubusercontent.com/halvardssm/deno-nessie/master/tests/column.test.ts
(E) error: Uncaught URIError: relative import path "std/testing/asserts.ts" not prefixed with / or ./ or ../ Imported from "https://raw.githubusercontent.com/halvardssm/deno-nessie/master/tests/column.test.ts"
(2) deno test https://raw.githubusercontent.com/halvardssm/deno-nessie/master/src/Column.ts
```

I'm feeding you back because you should consider that "import maps" maybe not be related to the original issue. The fact is that I was using the command line inappropriately. Newcomer's thing :)

Thank you!

**Comment by halvardssm** [comment]
@fvilante Actually, that was not a mistake from your part, but a problem with import maps. If you run it again but reload the cache, it should work for you.
`deno test --reload https://raw.githubusercontent.com/halvardssm/deno-nessie/master/tests/column.test.ts`

The error you were getting was complaining about the import of the file, since i was importing it with `import {...} from 'std/testing/asserts.ts'` instead of the whole url.

Have you considered joining the discord group for Deno? you can find the link on their website :)

**Comment by fvilante** [comment]
Wow. The `--reload` thing solved all problems I was experiencing.

Note: I've subscribed to Deno channel on discord.

Thank you a lot fpr your support!
